<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{

  function findlistBien(){

    return $this->getEntityManager()
    ->createQuery(
        'SELECT b, i, l, t FROM HTLImmobilierBundle:Bien b left Join b.images i Join b.typeBien t Join b.localite l WHERE b.etat = 1')
    ->getResult();
 
    }
}