<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * ProprietaireBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireBienRepository extends \Doctrine\ORM\EntityRepository
{
}
