<?php

namespace HTL\ImmobilierBundle\Repository;
use HTL\ImmobilierBundle\Entity\Bien;
use HTL\ImmobilierBundle\Entity\Image;
use HTL\ImmobilierBundle\Entity\Client;
use HTL\ImmobilierBundle\Entity\typeBien;
use HTL\ImmobilierBundle\Entity\Localite;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
/* SELECT c.nomComplet, c.adresse, b.nomBien, b.localite, b.type_bien, b.prixlocation, b.image, r FROM HTLImmobilierBundle:Reservation r

            left Join r.bien b Join r.client c WHERE r.etat = 0  

    SELECT DISTINCT c.nomComplet, c.adresse, r.dateReservation, b.nombien, i.image, l.libelle, b.prixlocation  
            FROM HTLImmobilierBundle:Reservation r, HTLImmobilierBundle:Localite l, HTLImmobilierBundle:Image i,HTLImmobilierBundle:typeBien t,
                    HTLImmobilierBundle:Client c,
            left Join  HTLImmobilierBundle:Bien b    
             join i WHERE b.id=i.bien_id 
            left join  t WHERE b.type_bien_id=t.id and c.id =r.client_id and r.etat=0
            */

    function findreservation(){

        return $this->getEntityManager()
        ->createQuery(
            'SELECT r.id, c.nomComplet, c.adresse, tb.libelle, b.nomBien, b.prixLocation, img.image, l.libelle, r.dateReservation
            FROM HTLImmobilierBundle:Reservation r 
            LEFT JOIN r.bien b JOIN b.typeBien tb join b.images img join b.localite l join r.client c
              where r.etat=  0')
      ->getResult();     
        }



        function showdetailreservation($id){

            return $this->getEntityManager()
        ->createQuery(
            'SELECT  c, b, tb, img, l
            FROM HTLImmobilierBundle:Reservation r 
            LEFT JOIN r.bien b JOIN b.typeBien tb join b.images img join b.localite l join r.client c
              where r.etat=0 and r.id= :id ')
        ->setParameter('id',$id)
        ->execute();


        }

}
